import getCurrentUser from "@/actions/getCurrentUser";
import getFavoriteUserRoom from "@/actions/getFavoriteUserRoom";
import CarouselRoomCard from "@/components/rooms/RoomCard";
import useRegisterModal from "@/hooks/useRegisterModal";
import { SafeRoom, SafeUser } from "@/types";
import { Box, Button, Grid, Typography } from "@mui/material";
import Head from "next/head";

type WishlistsProps = {
  favoriteRooms: SafeRoom[];
  currentUser: SafeUser;
};

const Wishlists = ({ favoriteRooms, currentUser }: WishlistsProps) => {
  const registerModal = useRegisterModal();

  return (
    <>
      <Head>
        <title>Wishlists - Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/airbnb-icon.svg" />
      </Head>
      <Box
        component="main"
        sx={{
          height: "80vh",
        }}
      >
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            width: "80%",
            marginInline: "auto",
            marginTop: "2rem",
            gap: 2,
          }}
        >
          <Typography variant="h4" component="h1">
            Wishlists
          </Typography>
          {currentUser ? (
            <>
              {favoriteRooms && favoriteRooms.length > 0 ? (
                <Grid
                  container
                  rowSpacing={1}
                  columnSpacing={{ xs: 1, sm: 2, md: 3 }}
                  sx={{
                    justifyContent: { xs: "center", md: "flex-start" },
                  }}
                >
                  {favoriteRooms.map((room) => (
                    <Grid item xs={12} sm={6} md={4} key={room.id}>
                      <CarouselRoomCard
                        key={room.id}
                        data={room}
                        currentUser={currentUser}
                      />
                    </Grid>
                  ))}
                </Grid>
              ) : (
                <Box>
                  <Typography variant="h6" component="h2">
                    Create your first wishlist
                  </Typography>
                  <Typography component="p">
                    As you search, click the heart icon to save your favorite
                    places and Experiences to a wishlist.
                  </Typography>
                </Box>
              )}
            </>
          ) : (
            <>
              <Box>
                <Typography variant="h6" component="h2">
                  Log in to view your wishlists
                </Typography>
                <Typography component="p">
                  You can create, view, or edit wishlists once you’ve logged in.
                </Typography>
              </Box>
              <Box>
                <Button
                  variant="contained"
                  size="large"
                  onClick={registerModal.onOpen}
                >
                  Log in
                </Button>
              </Box>
            </>
          )}
        </Box>
      </Box>
    </>
  );
};
export default Wishlists;

export async function getServerSideProps({ req, res }: any) {
  const favoriteRooms = await getFavoriteUserRoom(req, res);
  const currentUser = await getCurrentUser(req, res);
  return {
    props: {
      favoriteRooms,
      currentUser,
    },
  };
}
