import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";

const Login = () => {
  return (
    <>
      <Head>
        <title>AirBnb - Please login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/airbnb-icon.svg" />
      </Head>
      <div>
        <h1>I´m on route /login</h1>
      </div>
    </>
  );
};

export default Login;
