import getCurrentUser from "@/actions/getCurrentUser";
import getRoomsData from "@/actions/getRoomsData";
import CarouselRoomCard from "@/components/shared/rooms/RoomCard";
import RoomCardSkeleton from "@/components/shared/rooms/RoomCardSkeleton";
import { SafeRoom, SafeUser } from "@/types";
import { useIntersection } from "@mantine/hooks";
import { Container, Grid } from "@mui/material";
import { useInfiniteQuery } from "@tanstack/react-query";
import axios from "axios";
import Head from "next/head";
import { useEffect, useRef } from "react";
import type {
  NextApiRequest,
  NextApiResponse,
  GetServerSidePropsContext,
} from "next";

type HomeProps = {
  initialRooms: SafeRoom[];
  currentUser: SafeUser;
};

export default function Home({ initialRooms, currentUser }: HomeProps) {
  const { data, fetchNextPage, isFetchingNextPage, hasNextPage } =
    useInfiniteQuery(
      ["rooms"],
      async ({ pageParam = 1 }) => {
        const response = await axios.get(`/api/get-rooms?page=${pageParam}`);
        return response.data;
      },
      {
        getNextPageParam: (lastPage, allPages) => {
          if (lastPage.length === 0) {
            return null;
          }
          return allPages.length + 1;
        },
        initialData: {
          pages: [initialRooms],
          pageParams: [1],
        },
      }
    );
  const skeletonCount = 6;
  const skeletons = [...Array(skeletonCount)].map((_, i) => (
    <Grid item xs={12} sm={6} md={4} key={i}>
      <RoomCardSkeleton />
    </Grid>
  ));

  const lastRoomRef = useRef<HTMLElement>(null);
  const { ref, entry } = useIntersection({
    root: lastRoomRef.current,
    threshold: 1,
  });

  useEffect(() => {
    if (entry?.isIntersecting && hasNextPage) fetchNextPage();
  }, [entry, hasNextPage]);

  const rooms = data?.pages.flatMap((page) => page);

  return (
    <>
      <Head>
        <title>Vacation Homes & Condo Rentals - Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/airbnb-icon.svg" />
      </Head>

      <Container sx={{ my: "3rem", paddingBottom: "5rem" }}>
        <Grid
          container
          rowSpacing={1}
          columnSpacing={{ xs: 1, sm: 2, md: 3 }}
          px={"2rem"}
          sx={{
            justifyContent: { xs: "center", md: "flex-start" },
          }}
        >
          {rooms?.map((room, i) => (
            <Grid
              ref={i === rooms.length - 1 ? ref : null}
              item
              xs={12}
              sm={6}
              md={4}
              key={room.id}
            >
              <CarouselRoomCard data={room} currentUser={currentUser} />
            </Grid>
          ))}
          {isFetchingNextPage && hasNextPage && skeletons}
        </Grid>
      </Container>
    </>
  );
}

export async function getServerSideProps({ req, res }: any) {
  const initialRooms = await getRoomsData(1, 9);
  const currentUser = await getCurrentUser(req, res);
  return {
    props: {
      initialRooms,
      currentUser,
    },
  };
}
