import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Typography } from "@mui/material";
import { Button } from "@mui/material";
import Navbar from "@/components/Navbar/Navbar";
import ModalContainer from "@/components/modals/modal";
import SearchModal from "@/components/modals/SearchModal";
import CreateHomeModal from "@/components/modals/CreateHomeModal";

const inter = Inter({ subsets: ["latin"] });

export default  function Home() {
  return (
    <>
      <Head>
        <title>AirBnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/airbnb-icon.svg" />
      </Head>
      <main>
        <Navbar  />
        <ModalContainer />
        <SearchModal />
        <CreateHomeModal />
      </main>
    </>
  );
}
